name: Test
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install package
        run: |
          #sudo apt-get -y install build-essential gcc gfortran libblas-dev liblapack-dev
          sudo apt-get -y install libopenblas-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Test
        uses: onichandame/python-test-action@0.0.0
